version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run: sudo service docker stop
      - run:
          name: Install last version of Docker
          command: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build application Docker image
          command: docker image build -t pascalgrimaud/qualitoast:circleci .
      - run:
          name: Run docker-compose tests
          command: |
            docker-compose -f ./src/test/docker/docker-compose.test.yml up -d
            sleep 40
            docker-compose -f ./src/test/docker/docker-compose.test.yml logs
            docker container ps -a
            docker image ls
